name: Deploy static content to Pages

on:
  push:
    branches:
      - main  # The branch you want to deploy from
  workflow_dispatch:  # Allows manual triggering from GitHub Actions

permissions:
  contents: read  # Read access to repository content
  pages: write    # Write access to GitHub Pages
  id-token: write # For deploying to GitHub Pages

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Use the right version of checkout action

      - name: Set up Pages
        uses: actions/configure-pages@v2 # Set up GitHub Pages environment

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./ # This will deploy all files in the repository's root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
